### PR TITLE
[OK TO MERGE] Crud App

### LINKED ISSUE #5: FIX API
- [x] API broken fix it
- [x] gut s3 and user table usage
- [x] make it query user table info from room service on server/client side
- [x] confirm original seed works
- [x] confirm broken tests work

### LINKED ISSUE #9: extend the existing API to support 1 additional CRUD operation

### PR DESCRIPTION
**Pull request by cjm771**
Extend app functionality with crud services

resolves #5
resolves #9

image

- [x] Add 'add review' component to widget, with textbox and toggle-able button
- [x] create POST endpoint to recieve post
- [x] conduct proper error handling
- [x] upon successful submission, refresh reviews

### CODE REVIEW

**Comment by MengRS** [comment]
Starting review now...

**Comment by MengRS** [comment]
Data Loaded

**Comment by cjm771** [comment]
oh yes try increasing your writetimeout setting to 20000, (10x) see here from readme: 
image

**Comment by cjm771** [comment]
it looks like it seeded though? if so and you're getting that replicas error, try killing and restarting cassandra.
image

**Comment by MengRS** [comment]
@cjm771, everything went perfectly - thanks for you readme notes - should have paid better attention to those notes you had with handling potential cassandra install obstacles (tried your recs - and all was good)...

Here is my user experience in case you want to see it.

**Comment by cjm771** [comment]
Nice thanks yes i should put the time writeout and restarting cassandra in the installation notes since it seems it always happens. Thanks! also appreciate the review on my nonexistent house lol !!

**Comment by MengRS** [comment]
lol!👍🏼

**Pull request merged**
